version: "3.8"

services:
  old-school:
    image: openjdk:17
    container_name: old-school
    ports:
      - 8081:8081
    volumes:
      - ./docker_data:/app
      - projectfulldir:/data/npc/public/project_full_storage
    command: ["java", "-jar", "/app/old-school-0.0.1.jar", "--spring.config.location=file:/app/application.yml"]
    networks:
      - old-school-network
    depends_on:
      - postgres

  postgres:
    image: postgres
    container_name: old-school-postgres
    restart: always
    privileged: true
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    networks:
      - old-school-network
  
  nginx:
    image: nginx
    container_name: old-school-nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
      - ./nginx/logs:/var/log/nginx
    networks:
      - old-school-network
    depends_on:
      - old-school

volumes:
  postgres_data:
  projectfulldir:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /data/npc/public/project_full_storage

networks:
  old-school-network:
    driver: bridge
    name: old-school-network
